version: '3'
services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - ./Docker/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  db2:
    image: mysql:8
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - ./Docker/mysql1:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  nginx:
    image: nginx:1.13
    environment:
      APP_NAME: app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/
      - ./Docker/nginx:/usr/share/nginx/html
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Docker/nginx/logs:/var/log/nginx/
  app:
    build:
      args:
        WEB_USER_ID: 1000
        WEB_USER_NAME: cahtel
      context: Docker/app
    volumes:
      - ./:/var/www
      - ./Docker/app/php.ini:/usr/local/etc/php/custom.d